env:

build:

config:
  apiUrl: /api/

  title: ~
  titleIcon: ~

  locales: ~
  defaultLocale: ~
  detectLocaleByClientIpAddress: true

  pushNotifications:
    guestEnabled: false
    userEnabled: false
